name: health_care_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  fluttertoast: ^8.2.10
  dartz: ^0.10.1
  calendar_day_slot_navigator: ^0.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  #helana
  table_calendar: ^3.0.9
  # Routing
  go_router: ^14.3.0
  # Loading indicator
  flutter_easyloading: ^3.0.5
  # Device preview
  device_preview: ^1.2.0
  # Responsive UI
  flutter_screenutil: ^5.9.3
  #firebase 
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  #calculate time ago
  timeago: ^3.7.0
  #for random id
  uuid: ^4.5.1
  http: ^1.4.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/health.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/man.png
    - assets/icons/
    - lib/core/assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/static/Cairo-Black.ttf
        - asset: assets/fonts/static/Cairo-Bold.ttf
        - asset: assets/fonts/static/Cairo-Medium.ttf
        - asset: assets/fonts/static/Cairo-Regular.ttf
