enum DoctorSpecialty {
  cardiologist,
  dentist,
  dermatologist,
  endocrinologist,
  gastroenterologist,
  generalPractitioner,
  gynecologist,
  neurologist,
  oncologist,
  ophthalmologist,
  orthopedic,
  pediatrician,
  psychiatrist,
  pulmonologist,
  rheumatologist,
  urologist,
}

enum DoctorSpecialtyName {
  cardiology,
  dentistry,
  dermatology,
  endocrinology,
  gastroenterology,
  generalMedicine,
  gynecology,
  neurology,
  oncology,
  ophthalmology,
  orthopedics,
  pediatrics,
  psychiatry,
  pulmonology,
  rheumatology,
  urology,
}
