// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_N9wQHHfjjfmajN7L8aCHOIFAqRYQ6EU',
    appId: '1:104390503465:web:973e006e0617fc81f84038',
    messagingSenderId: '104390503465',
    projectId: 'health-care-d663d',
    authDomain: 'health-care-d663d.firebaseapp.com',
    storageBucket: 'health-care-d663d.firebasestorage.app',
    measurementId: 'G-1743WH371J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa13k-FQXfpbWyoLaNtogbSWG1PjrbZD0',
    appId: '1:104390503465:android:abd68a8735e39457f84038',
    messagingSenderId: '104390503465',
    projectId: 'health-care-d663d',
    storageBucket: 'health-care-d663d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuh1jQZBWKIYt0uucxGG2cv_uutZ_4Zbk',
    appId: '1:104390503465:ios:e484b8f6391251e9f84038',
    messagingSenderId: '104390503465',
    projectId: 'health-care-d663d',
    storageBucket: 'health-care-d663d.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuh1jQZBWKIYt0uucxGG2cv_uutZ_4Zbk',
    appId: '1:104390503465:ios:e484b8f6391251e9f84038',
    messagingSenderId: '104390503465',
    projectId: 'health-care-d663d',
    storageBucket: 'health-care-d663d.firebasestorage.app',
    iosBundleId: 'com.example.healthCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_N9wQHHfjjfmajN7L8aCHOIFAqRYQ6EU',
    appId: '1:104390503465:web:641f9abd364a3d1bf84038',
    messagingSenderId: '104390503465',
    projectId: 'health-care-d663d',
    authDomain: 'health-care-d663d.firebaseapp.com',
    storageBucket: 'health-care-d663d.firebasestorage.app',
    measurementId: 'G-ZDVSWNVXNM',
  );
}
